about_us/urls.py
from django.conf.urls import url
from django.urls import path
from .views import about_us

app_name = "about_us"

urlpatterns = [
    path('', about_us, name='about_us'),
]

donation/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import donasi, submit

app_name = 'donation'

urlpatterns = [
	path('', donasi, name="donasi"),
	path('fail/', submit, name='submit'),
]

funding_project/urls.py
from django.contrib import admin
from django.urls import path, include
import donation
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('login/', include('login.urls')),
    path('program/', include('programs_app.urls')),
    path('donasi/', include('donation.urls')),
    path('mydonation/', include('mydonations.urls')),
	path('about_us/', include('about_us.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

hello_world/urls.py
from django.conf.urls import url
from django.urls import path
from .views import hello_world

urlpatterns = [
    path('', hello_world, name='Hello World'),
]

login/urls.py
from django.urls import path
from . import views
# Create your views here.

app_name = 'login'
urlpatterns = [
	path('loged/', views.loged, name = 'loged'),
	path('', views.login, name = 'login'),
	path('logout/', views.logout, name = 'logout'),
]

mydonations/urls.py
from django.conf.urls import url
from django.urls import path
from .views import mydonations, get_account_donation

app_name = "mydonation"

urlpatterns = [
    path('', mydonations, name='mydonations'),
    path('get_account_donation/', get_account_donation, name='get_account_donation'),
    # path('get_donation_api/', get_donation_api, name='get_donation_api'),
]

news/urls.py
from django.conf.urls import url
from django.urls import path
from .views import news

app_name = "news"

urlpatterns = [
    path('', news, name='news'),
]

programs_app/urls.py
from django.conf.urls import url
from django.urls import path
from .views import programs


app_name = "programs_app"


urlpatterns = [
    path('', programs, name='programs'),
]

about_us/models.py
from django.db import models

# Create your models here.

class Aboutus(models.Model):
    name = models.CharField(max_length=60)
    text = models.TextField(max_length=300)

    def __str__(self):
        return self.name

donation/models.py
from django.db import models


# Create your models here.
class ModelDonasi(models.Model):
	namaProgram = models.CharField(max_length=200)
	email = models.EmailField(max_length=200, null=True)
	uang = models.IntegerField()

hello_world/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

mydonations/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models

# Create your models here.

programs_app/models.py
from django.db import models

# Create your models here.

class Program(models.Model):
    image = models.ImageField() # kasih default = 'something.jpg'
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=300)

donation/forms.py
from django import forms
from .models import ModelDonasi

class FormDonasi(forms.ModelForm):
	namaProgram = forms.CharField(max_length=100, label='Nama Program', widget=
					forms.TextInput(attrs= {'class' : 'form-control','placeholder' : 'Nama Program' }))
	uang = forms.CharField(label='Jumlah Donasi', widget=
					forms.NumberInput(attrs= {'class' : 'form-control','placeholder' : 'Jumlah Donasi' }))
	class Meta:
		model = ModelDonasi
		fields = ('namaProgram', 'uang')

about_us/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .models import Aboutus

# Create your views here.
content = {}


def about_us(request):
    content['is_login'] = True
    content['data'] = list(Aboutus.objects.all())
    return render(request, 'about_us.html', content)


def cerita(request):
    if request.method == 'POST':
        text = request.POST['text']
        name = request.session['name']
        Aboutus.objects.create(name=name, text=text)
        return JsonResponse({'saved': True})
    return JsonResponse({'saved': False})

def saveCerita(request):
    if request.method == 'POST':
        text = request.POST['text']
        name = request.user.first_name + " " + request.user.last_name
        Aboutus.objects.create(name=name, text=text)
        return JsonResponse({'saved': True, 'name': name, 'text': text})
    return JsonResponse({'saved': False})

donation/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import FormDonasi
from .models import ModelDonasi
from django.urls import reverse

# Create your views here.
def donasi(request):
	if (request.user.is_authenticated):
		form = FormDonasi(request.POST or None)
		response = {'form' : form, 'D' : ModelDonasi.objects.all()}
		return render(request, 'donasi.html', response)
		
	else:
		return redirect(reverse('login:login'))



def submit(request):
	if(request.method == 'POST'):
		form = FormDonasi(request.POST or None)
		namaProgram = request.POST['namaProgram']
		#nama = request.POST['nama']
		email = request.user.email
		uang = request.POST['uang']
		donasi = ModelDonasi.objects.create(namaProgram=namaProgram, email=email, uang=uang)
		donasi.save()
		return redirect('donation:donasi')
	else:
		return redirect('donation:donasi')

hello_world/views.py
from django.shortcuts import render

# Create your views here.

response = {}
def hello_world(request):
    return render(request, 'hello_world.html', response)

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as out

# Create your views here.
def login(request):
	return render(request, "login.html", {})

def loged(request):
	if (request.user.is_authenticated):
		request.session['user_email'] = request.user.email
		nama = request.user.first_name + " " + request.user.last_name
		nama = nama.upper()
		return render(request, "loged.html", {'nama' : nama})
	else:
		return redirect('login:login') 

def logout(request):
	request.session.flush()
	out(request)
	return redirect('login:login')

mydonations/views.py
from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from donation.models import ModelDonasi
import requests

# Create your views here.

response = {}
def mydonations(request):
	if (request.user.is_authenticated):
		# If user already login, render the page
		response['title'] = 'A9 Funding - Donasi Saya'		
		response['list_of_donations'] = ModelDonasi.objects.filter(email = request.user.email)
		return render(request, 'mydonations.html', response)
	else:
		return HttpResponseRedirect(reverse('login:login'))

def get_account_donation(request):
	data = ModelDonasi.objects.filter(email = request.user.email)
	data_json = serializers.serialize('json', data)
	# response = requests.get(reverse('mydonations:get_donation_api'))
	# donation_data = response.json()
	donation_queries = {'donations': list()}

	for donation in data_json:
		new_donation = {'nama_program':'', 'uang':''}
		observed_donation = donation['fields']
		# if observed_donation["email"] == request.use
		if 'namaProgram' in observed_donation:
			new_donation['nama_program'] = observed_donation['namaProgram']
		
		if 'uang' in observed_donation:
			new_donation['uang'] = observed_donation['uang']
		
		donation_queries.append(new_donation)
	return JsonResponse(donation_queries)

""" def get_donation_api():
	data = ModelDonasi.objects.all()
	data_json = serializers.serialize('json', data)
	return data_json """
	# return JsonResponse(data, safe=False)

news/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

def news(request):
    response = {}
    html = 'index.html'
    return render(request,html,response)

programs_app/views.py
from django.shortcuts import render
from .models import Program

# Create your views here.

response = {}
def programs(request):
	response['title'] = 'A9 Funding - Program'
	response['all_programs'] = Program.objects.all().values()
	return render(request, 'programs.html', response)

about_us/templates/about_us.html
{% extends 'navbar.html' %}

{% block head %}
<!DOCTYPE html>
<html>
{% load static %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>{{title}}</title>
<style>
	html, body
	{
		height: 100%;
	}
	
	body
	{
		margin: 0px;
		padding: 0px;
		background: #2056ac;
		font-family: 'Questrial', sans-serif;
		font-size: 12pt;
		color: rgba(0,0,0,.6);
	}
	
	
	h1, h2, h3
	{
		margin: 0;
		padding: 0;
		color: #404040;
	}
	
	p, ol, ul
	{
		margin-top: 0;
	}
	
	ol, ul
	{
		padding: 0;
		list-style: none;
	}
	
	p
	{
		line-height: 180%;
	}
	
	strong
	{
	}
	
	a
	{
		color: #2056ac;
	}
	
	a:hover
	{
		text-decoration: none;
	}
	

	.container
	{
		margin: 0px auto;
		width: 1200px;
	}
	

		form
		{
		}
		
			form label
			{
				display: block;
				text-align: left;
				margin-bottom: 0.5em;
			}
			
			form .submit
			{
				margin-top: 2em;
				line-height: 1.5em;
				font-size: 1.3em;
			}
		
			form input.text,
			form select,
			form textarea
			{
				position: relative;
				-webkit-appearance: none;
				display: block;
				border: 0;
				background: #fff;
				background: rgba(255,255,255,0.75);
				width: 100%;
				border-radius: 0.50em;
				margin: 1em 0em;
				padding: 1.50em 1em;
				box-shadow: inset 0 0.1em 0.1em 0 rgba(0,0,0,0.05);
				border: solid 1px rgba(0,0,0,0.15);
				-moz-transition: all 0.35s ease-in-out;
				-webkit-transition: all 0.35s ease-in-out;
				-o-transition: all 0.35s ease-in-out;
				-ms-transition: all 0.35s ease-in-out;
				transition: all 0.35s ease-in-out;
				font-size: 1em;
				outline: none;
			}

				form input.text:hover,
				form select:hover,
				form textarea:hover
				{
				}

				form input.text:focus,
				form select:focus,
				form textarea:focus
				{
					box-shadow: 0 0 2px 1px #E0E0E0;
					background: #fff;
				}
				
				form textarea
				{
					min-height: 12em;
				}

				form .formerize-placeholder
				{
					color: #555 !important;
				}

				form ::-webkit-input-placeholder
				{
					color: #555 !important;
				}

				form :-moz-placeholder
				{
					color: #555 !important;
				}

				form ::-moz-placeholder
				{
					color: #555 !important;
				}

				form :-ms-input-placeholder
				{
					color: #555 !important;
				}

				form ::-moz-focus-inner
				{
					border: 0;
				}

	.image
	{
		display: inline-block;
		border: 1px solid rgba(0,0,0,.1);
	}
	
	.image img
	{
		display: block;
		width: 100%;
	}
	
	.image-full
	{
		display: block;
		width: 100%;
		margin: 0 0 3em 0;
	}
	
	.image-left
	{
		float: left;
		margin: 0 2em 2em 0;
	}
	
	.image-centered
	{
		display: block;
		margin: 0 0 2em 0;
	}
	
	.image-centered img
	{
		margin: 0 auto;
		width: auto;
	}


	ul.style1
	{
	}

		

	.title
	{
		margin-bottom: 3em;
	}
	
	.title h2
	{
		font-size: 2.8em;
	}
	
	.title .byline
	{
		font-size: 1.1em;
		color: #6F6F6F#;
	}



	#header-wrapper
	{
		overflow: hidden;
		background: #2056ac;
	}

	#header
	{
		text-align: center;
	}


	#logo
	{
		padding: 8em 0em 4em 0em;
	}
	
	#logo h1
	{
		display: block;
		margin-bottom: 0.20em;
		padding: 0.20em 0.9em;
		font-size: 3.5em;
	}
	
	#logo a
	{
		text-decoration: none;
		color: #FFF;
	}
	
	
	

	#banner
	{
		padding-top: 5em;
	}



	.wrapper
	{
		overflow: hidden;
		padding: 0em 0em 5em 0em;
		background: #FFF;
	}

	#wrapper1
	{
		background: #FFF;
	}

	#wrapper2
	{
		overflow: hidden;
		background: #F3F3F3;
		padding: 5em 0em;
		text-align: center;
	}

	#wrapper3
	{
	}
	
	#wrapper4
	{
	}


	#welcome
	{
		overflow: hidden;
		width: 1000px;
		padding: 6em 100px 0em 100px;
		text-align: center;
	}
	
	#welcome .content
	{
		padding: 0em 8em;
	}
	
	#welcome .title h2
	{
	}
	
	#welcome a,
	#welcome strong
	{
	}

	#sidebar
	{
		float: right;
		width: 350px;
	}


	#portfolio
	{
		overflow: hidden;
		padding-top: 5em;
		border-top: 1px solid rgba(0,0,0,0.2);
	}
	
	#portfolio .box
	{
		text-align: center;
		color: rgba(0,0,0,0.5);
	}
	
	#portfolio h3
	{
		display: block;
		padding-bottom: 1em;
		font-size: 1em;
		color: rgba(0,0,0,0.6);
	}

	#portfolio .title
	{
		text-align: center;
	}

	#portfolio .title h2
	{
		color: rgba(0,0,0,0.8);
	}

	.column1,
	.column2,
	.column3,
	.column4
	{
		width: 250px;
	}
	
	.column1,
	.column2,
	.column3
	{
		float: left;
		margin-right: 24px;
	}
	
	.column4
	{
		float: right;
	}
	
	
	
	

	

.judul_about {
    font-family: 'Montserrat', sans-serif;
    font-size: 32px;
    color: white;
    font-weight: bold;
    text-align: center;
    margin: 3rem 0 1rem;
}


.container_about {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 10rem 8rem;
}

.background_testimoni {
    margin: auto;
}

.judul_testimoni {
    font-family: 'Montserrat', sans-serif;
    text-align: center;
    font-size: 32px;
    color: #313131;
    font-weight: bold;
    padding-bottom: 3rem;
}

.text-area {
    border-radius: 12px;
    box-shadow: 0px 2px 4px rgba(0, 0, 0, .16);
    padding: 1rem;
    font-family: 'Montserrat', sans-serif !important;
    font-size: 16px;
}

.form-group {
    margin: auto 10rem;
}

.submit-btn {
    padding-top: 1rem;
}

.testimonials-form {
    padding: 6rem ;
}

.btn-primary {
    background-color: #00BCD4;
    color: white;
    font-weight: bold;
    border: 2px solid #0096AA;
    border-radius: 40px;
    width: 200px;
    height: 48px;
    text-align: center;
    font-family: 'Montserrat', sans-serif !important;
    font-size: 18px;
}

.testimony-set  {
    background-color: #FFFFFF;
    border-radius: 16px;
    box-shadow: 0px 2px 4px rgba(0, 0, 0, .16);
    width: 18rem;
    height: 12rem;
    margin: 2rem 2rem;
}

@media screen and (max-width: 991px) {
    .container_about {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        padding: 2rem 2rem;
    }

    .about {
        font-family: 'Montserrat', sans-serif;
        font-size: 24px;
        color: white;
        padding: 1rem 1rem;
        text-align: center;
    }

    .judul_testimoni {
        font-family: 'Montserrat', sans-serif;
        text-align: center;
        font-size: 32px;
        color: #313131;
        font-weight: bold;
        padding-bottom: 3rem;
    }

    .text-area {
        border-radius: 12px;
        box-shadow: 0px 2px 4px rgba(0, 0, 0, .16);
        padding: 1rem;
        font-family: 'Montserrat', sans-serif !important;
        font-size: 16px;
    }

    .form-group {
        margin: auto 2rem;
    }

    .submit-btn {
        padding-top: 2rem;
    }

    .testimonials-form {
        padding: 3rem 0;
    }

    .submit-btn {
        display: flex !important;
        justify-content: center !important;
        align-items: center !important;
    }
}

</style>
<meta name="keywords" content="" />
<meta name="description" content="" />
<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

<link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Quicksand:400,700|Questrial" rel="stylesheet" />
<link href="default.css" rel="stylesheet" type="text/css" media="all" />
<link href="fonts.css" rel="stylesheet" type="text/css" media="all" />

</head>
<body>
<div id="header-wrapper">
	<div id="header" class="container">
		<div id="logo">
			<h1><a href="#">PT. Sinar Perak</a></h1>
		</div>
	</div>
</div>
<div class="wrapper">
	<div id="banner" class="container"><img src="{%static 'img/bantuan1.jpg'%}" width="1200" height="500" alt="" /></div>
	<div id="welcome" class="container">
    	
<div class="title">
	  <h2>About Us</h2>
		</div>
		<p>PT Sinar Mas adalah perusahaan yang bergerak di bidang sosial. A9 adalah solusi untuk menyelesaikan masalah finansial untuk orang yang membutuhkan dengan membuka galang dana yang nantinya akan disalurkan ke orang yang membutuhkan. karna kami adalah orang baik.</p>
	</div>
	<div id="portfolio" class="container">
		<div class="column1">
			<div class="box">
			  <h3>Bersahabat</h3>
				<p>Membantu orang dengan cara bersahabat.</p>
		</div>
		</div>
		<div class="column2">
			<div class="box">
			  <h3>Dekat</h3>
				<p>Dekat dengan semua orang.</p>
		</div>
		</div>
		<div class="column3">
			<div class="box">
			  <h3>Membantu</h3>
				<p>Membantu tanpa melihat apapun</p>
		  </div>
		</div>
		<div class="column4">
			<div class="box">
			  <h3>Baik Hati</h3>
				<p>Kami yang terbaik hatinya</p>
		 </div>
		</div>
	</div>
	<div id="three-column" class="container">
		<div><span class="arrow-down"></span></div>
		


		
<div class="background_testimoni">
    {% if user.is_authenticated %}
        <section class="testimonials-form">
            <div class="title-with-line d-flex justify-content-center align-items-center flex-column">
                <h1 align="center" class="judul_testimoni"> Ceritakan Kami </h1>
            </div>
            {% csrf_token %}
            <div class="form-group">
        <textarea class="form-control text-area" rows=10
                  id="text_testimoni"></textarea>
                <div class="submit-btn d-flex justify-content-end align-items-center">
                    <input type="button"  onclick="testimoni()" class="btn-primary btn" value="SUBMIT">
                </div>
            </div>

        </section>
    {% endif %}

    <section class="testimonials-list">
        <div class="title-with-line d-flex justify-content-center align-items-center flex-column">
        </div>
        <div id="testimony" class="testimony d-flex flex-wrap justify-content-center align-items-center">
            {% for testimony in data %}
                <div class="testimony-set d-flex justify-content-center align-items-center flex-column">
                    <p class="testimony-txt">“{{ testimony.text }}” </p>
                    <p class="testimoners"><strong>{{ testimony.name }}</strong></p>
                </div>
            {% endfor %}
            <div class="blank-space"></div>
            <div class="blank-space"></div>
        </div>
    </section>

</div>
</div>
</body>

<script>
function testimoni() {
    var csrftoken = $("[name=csrfmiddlewaretoken]").val();
    var text = $('#text_testimoni').val();
    $.ajax({
        method: "POST",
        url: "/tentangKami/save/",
        headers: {
            "X-CSRFToken": csrftoken,
        },
        data: {
            text: text,
        },
        success: function (result) {
            if (result.saved) {
                var html = `<div class="testimony-set d-flex justify-content-center align-items-center flex-column"><p class="testimony-txt">“${result.text}”</p><p class="testimoners"><strong>${result.name}</strong></p></div>`;
                $('#testimony').prepend(html);
                $('#text_testimoni').val('');
            }
        },
        error: function () {
            alert("Error, cannot save data to server");
        }


    })
}
</script>
</html>
{% endblock %}

donation/templates/donasi.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
        <!-- BOOSTRAP -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <title>A9 Funding - Donasi</title>
</head>
<body class = bg-light>
    {% include "navbar.html" %}
    <div class="container-fluid">
        <div class='row'>
            <div class = "col-sm-1">
            </div>

            <div class="col-sm-10">
                <br><br><br><br>
                <div>
                    <h1 style = "font-family: 'Montserrat';">Donasi Sekarang
                    </h1>
                    <hr style = "border-color: #0086CD; border-width: 2px;">
                </div>
                <div>
                    <form class="ui form"action={% url 'donation:submit' %} method="POST">
                        <div style="border-radius:10%">
                            <div class="card-body text-white" style = "background-color: #0086CD; font-size: 22px; font-family: 'Montserrat'; margin: auto; width: 100%;">
                            {% csrf_token %}
                            {{form.as_p}}
                            </div>
                        </div>
                        </div>
                        <br><br>
                        <button class="btn  text-white item-right" type="submit" value="Submit" style = "background-color: #0086CD; font-family: 'Montserrat'; font-size: 27px">Submit</button>
                    </form>
                </div>
            </div>

            <div class = "col-sm-1">
            </div>
        </div>
    </div>


</body>
</html>

hello_world/templates/hello_world.html
<!DOCTYPE html>
<html>
    <head>
        <title>Hello world!</title>
    </head>

    <body>
        <h1>Hello world!</h1>
        <hr>
        <h2>This website is currently under construction by Team A9.</h2>
    </body>
</html>

news/templates/index.html
{% extends 'navbar.html' %}
{% load static %}
{% block head %}
<!DOCTYPE html>
<html>
    <head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <title>A9 Funding</title>
        <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
	<body>
	<br>
	<h1 style="width:50%; margin:5% 5% 5% 20%;"> Berita Terkini</h1>
	 <div class="card" style="width:50%; margin:5% 5% 5% 25%;">
	 <div class="row">
		 <div class="col-md-4">
			<img src="{%static 'img/gambar.jpeg'%}" alt="" height = "100%" width = "100%">
		</div>
		<div class="col-md-8">
			<h4 class="card-title">Mari Bantu Sulteng, Donasi Dompet Amal Transmedia</h4>
			<p class="card-text">Jakarta - Bantuan masih terus mengalir untuk korban gempa dan tsunami di Sulawesi Tengah (Sulteng). Hingga saat ini, bantuan lewat Dompet Amal Transmedia mencapai Rp 7,4 miliar.</p>
			<a href="{% url 'programs_app:programs' %}" class="btn btn-primary">Donasi</a>
		</div>
    
    </div>
	</div>
	
	
	<div class="card" style="width:50%; margin:5% 5% 5% 25%;">
	 <div class="row">
	 <div class="col-md-4">
            <img src="{%static 'img/gambar.jpeg'%}" alt="" height = "100%" width = "100%">
        </div>
        <div class="col-md-8">
            <h4 class="card-title">Mataram Diguncang Gempa Magnitudo 5,1</h4>
            <p class="card-text">Jakarta - Gempa bermagnitudo 5,1 terjadi di Mataram, Nusa Tenggara Barat. Berdasarkan data Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) lindu terjadi pukul 09:37:15 WIB.</p>
            <a href="{% url 'programs_app:programs' %}" class="btn btn-primary">Donasi</a>
        </div>
	 </div>
	 </div>
	<div class="card" style="width:50%; margin:5% 5% 5% 25%;">
	 <div class="row">
	 <div class="col-md-4">
            <img src="{%static 'img/gambar.jpeg'%}" alt="" height = "100%" width = "100%">
        </div>
        <div class="col-md-8">
            <h4 class="card-title">Situbondo Terkena Gempa</h4>
            <p class="card-text">Jakarta - Bantuan masih terus mengalir untuk korban gempa Situbondo. Hingga saat ini, bantuan lewat Dompet Amal Kitabisa.com mencapai Rp 2 miliar.</p>
            <a href="{% url 'programs_app:programs' %}" class="btn btn-primary">Donasi</a>
        </div>
	 </div>
	</div>
	
	</body>
        
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

{% endblock %}