about_us/urls.py
from django.conf.urls import url
from django.urls import path
from .views import about_us

app_name = "about_us"

urlpatterns = [
    path('', about_us, name='about_us'),
]

donation/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import donasi, submit

app_name = 'donation'

urlpatterns = [
	path('', donasi, name="donasi"),
	path('fail/', submit, name='submit'),
]

funding_project/urls.py
from django.contrib import admin
from django.urls import path, include
import donation
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('login/', include('login.urls')),
    path('program/', include('programs_app.urls')),
    path('donasi/', include('donation.urls')),
    path('mydonation/', include('mydonations.urls')),
	path('about_us/', include('about_us.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

hello_world/urls.py
from django.conf.urls import url
from django.urls import path
from .views import hello_world

urlpatterns = [
    path('', hello_world, name='Hello World'),
]

login/urls.py
from django.urls import path
from . import views
# Create your views here.

app_name = 'login'
urlpatterns = [
	path('loged/', views.loged, name = 'loged'),
	path('', views.login, name = 'login'),
	path('logout/', views.logout, name = 'logout'),
]

mydonations/urls.py
from django.conf.urls import url
from django.urls import path
from .views import mydonations, get_account_donation

app_name = "mydonation"

urlpatterns = [
    path('', mydonations, name='mydonations'),
    path('get_account_donation/', get_account_donation, name='get_account_donation'),
    # path('get_donation_api/', get_donation_api, name='get_donation_api'),
]

news/urls.py
from django.conf.urls import url
from django.urls import path
from .views import news

app_name = "news"

urlpatterns = [
    path('', news, name='news'),
]

programs_app/urls.py
from django.conf.urls import url
from django.urls import path
from .views import programs


app_name = "programs_app"


urlpatterns = [
    path('', programs, name='programs'),
]

about_us/models.py
from django.db import models

# Create your models here.

class Aboutus(models.Model):
    name = models.CharField(max_length=60)
    text = models.TextField(max_length=300)

    def __str__(self):
        return self.name

donation/models.py
from django.db import models


# Create your models here.
class ModelDonasi(models.Model):
	namaProgram = models.CharField(max_length=200)
	email = models.EmailField(max_length=200, null=True)
	uang = models.IntegerField()

hello_world/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

mydonations/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models

# Create your models here.

donation/forms.py
from django import forms
from .models import ModelDonasi

class FormDonasi(forms.ModelForm):
	namaProgram = forms.CharField(max_length=100, label='Nama Program', widget=
					forms.TextInput(attrs= {'class' : 'form-control','placeholder' : 'Nama Program' }))
	uang = forms.CharField(label='Jumlah Donasi', widget=
					forms.NumberInput(attrs= {'class' : 'form-control','placeholder' : 'Jumlah Donasi' }))
	class Meta:
		model = ModelDonasi
		fields = ('namaProgram', 'uang')

about_us/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .models import Aboutus

# Create your views here.
content = {}


def about_us(request):
    content['is_login'] = True
    content['data'] = list(Aboutus.objects.all())
    return render(request, 'about_us.html', content)


def cerita(request):
    if request.method == 'POST':
        text = request.POST['text']
        name = request.session['name']
        Aboutus.objects.create(name=name, text=text)
        return JsonResponse({'saved': True})
    return JsonResponse({'saved': False})

def saveCerita(request):
    if request.method == 'POST':
        text = request.POST['text']
        name = request.user.first_name + " " + request.user.last_name
        Aboutus.objects.create(name=name, text=text)
        return JsonResponse({'saved': True, 'name': name, 'text': text})
    return JsonResponse({'saved': False})

donation/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import FormDonasi
from .models import ModelDonasi
from django.urls import reverse

# Create your views here.
def donasi(request):
	if (request.user.is_authenticated):
		form = FormDonasi(request.POST or None)
		response = {'form' : form, 'D' : ModelDonasi.objects.all()}
		return render(request, 'donasi.html', response)
		
	else:
		return redirect(reverse('login:login'))



def submit(request):
	if(request.method == 'POST'):
		form = FormDonasi(request.POST or None)
		namaProgram = request.POST['namaProgram']
		#nama = request.POST['nama']
		email = request.user.email
		uang = request.POST['uang']
		donasi = ModelDonasi.objects.create(namaProgram=namaProgram, email=email, uang=uang)
		donasi.save()
		return redirect('donation:donasi')
	else:
		return redirect('donation:donasi')

hello_world/views.py
from django.shortcuts import render

# Create your views here.

response = {}
def hello_world(request):
    return render(request, 'hello_world.html', response)

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as out

# Create your views here.
def login(request):
	return render(request, "login.html", {})

def loged(request):
	if (request.user.is_authenticated):
		request.session['user_email'] = request.user.email
		nama = request.user.first_name + " " + request.user.last_name
		nama = nama.upper()
		return render(request, "loged.html", {'nama' : nama})
	else:
		return redirect('login:login') 

def logout(request):
	request.session.flush()
	out(request)
	return redirect('login:login')

mydonations/views.py
from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from donation.models import ModelDonasi
import requests

# Create your views here.

response = {}
def mydonations(request):
	if (request.user.is_authenticated):
		# If user already login, render the page
		response['title'] = 'A9 Funding - Donasi Saya'		
		response['list_of_donations'] = ModelDonasi.objects.filter(email = request.user.email)
		return render(request, 'mydonations.html', response)
	else:
		return HttpResponseRedirect(reverse('login:login'))

def get_account_donation(request):
	data = ModelDonasi.objects.filter(email = request.user.email)
	data_json = serializers.serialize('json', data)
	# response = requests.get(reverse('mydonations:get_donation_api'))
	# donation_data = response.json()
	donation_queries = {'donations': list()}

	for donation in data_json:
		new_donation = {'nama_program':'', 'uang':''}
		observed_donation = donation['fields']
		# if observed_donation["email"] == request.use
		if 'namaProgram' in observed_donation:
			new_donation['nama_program'] = observed_donation['namaProgram']
		
		if 'uang' in observed_donation:
			new_donation['uang'] = observed_donation['uang']
		
		donation_queries.append(new_donation)
	return JsonResponse(donation_queries)

""" def get_donation_api():
	data = ModelDonasi.objects.all()
	data_json = serializers.serialize('json', data)
	return data_json """
	# return JsonResponse(data, safe=False)

news/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

def news(request):
    response = {}
    html = 'index.html'
    return render(request,html,response)

templates/navbar.html
{% block head %}
{% endblock %}
{% load static %}
		
        <!-- For Bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
		
        <!-- Own's static files -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/tp1.css' %}">
	</head>
	
    <body>
    	<!-- from bootstrap -->
    		<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="navBar" style="background-color: #0086CD;">
	            <a class="nav-item nav-link" href="{% url 'news:news' %}"><img id="nine-logo" src="{% static 'img/nine-logo.png' %}"></a>
			    
			    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
			        <span class="navbar-toggler-icon"></span>
			    </button>
			    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
				    <div class="navbar-nav" id="navBarNav">
				    	<a class="nav-item nav-link nav-head" href="{% url 'programs_app:programs' %}" style="color: #FFFFFF;">Program</a>
						<a class="nav-item nav-link nav-head" href="{% url 'donation:donasi' %}" style="color: #FFFFFF;">Donasi</a>
						{% if user.is_authenticated %}
							<a class="nav-item nav-link nav-head" href="{% url 'mydonation:mydonations' %}" style="color: #FFFFFF;">Donasi Saya</a>
						{% endif %}

						<a class="nav-item nav-link nav-head" href="{% url 'about_us:about_us' %}" style="color: #FFFFFF;">About Us</a>

						{% if user.is_authenticated %}
							<a class="nav-item nav-link nav-head" id="navDaftar" href="{% url 'login:logout' %}" style="color: #FFFFFF;">Logout</a>
						{% else %}
							<a class="nav-item nav-link nav-head" id="navDaftar" href="{% url 'login:login' %}" style="color: #FFFFFF;">Login</a>
						{% endif %}
				    </div>
			    </div>

			</nav>
    		
		{% block content %}
		{% endblock %}